services:
  database:
    image: mariadb:latest
    restart: no
    ports:
      - 3307:3306
    container_name: database
    volumes:
      - ./db_data:/var/lib/mysql
      - ./videothek001.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=test

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    container_name: pma
    ports:
      - 8280:80
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 100M
    restart: no

volumes:
  db_data:
